[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.21"
optimizer_runs = 100000
via_ir = false

fs_permissions = [{ access = "read", path = "./test/users.json"}, { access = "read-write", path = "./test/output.csv" }]

[rpc_endpoints]
base = "${BASE_RPC}"
tenderly = "${TENDERLY_FORK_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
