[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.21"
optimizer_runs = 100000
via_ir = false

[rpc_endpoints]
base = "${BASE_RPC}"
tenderly = "${TENDERLY_FORK_RPC_URL}"

[etherscan]
tenderly = { key = "${TENDERLY_ACCESS_KEY}", chain = "1337", url = "${TENDERLY_VERIFY_URL}" } # this is bugged in Foundry but hopefully will work on newer version of Foundry

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
